language: ruby
dist: trusty
cache:
  bundler: true
  directories:
    - node_modules
sudo: required

# Uncomment to have screenshots dumped to S3
# You will need to provide S3 information to travis as we do not have one for EDSC
addons:
  # artifacts:
  #   debug: true
  #   paths:
  #     - capybara
  #   target_paths: $TRAVIS_BUILD_NUMBER
  #   working_dir: tmp/
  #   bucket: $ARTIFACTS_BUCKET
  #   s3_region: us-east-1
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
  - bundle exec bin/setup_travis
  - bundle exec rake travis:ci
env:
  global:
    - CI_NODE_TOTAL=4
  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1
    - CI_NODE_INDEX=2
    - CI_NODE_INDEX=3
    - JASMINE=true
branches:
  only: # Only build master and e2e-services. All pull requests also get built
    - master
    - e2e-services
deploy:
  provider: script
  script: bin/ecc-sync
  on:
    branch: master
    repo: nasa/earthdata-search
